[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "glama"
version = "0.0.1"
dependencies = [
  "pycairo",
  "PyGObject",
  "openai"
]
[project.optional-dependencies]
dev = ["requirements-parser", "setuptools"]
